# Variables:
# %player% - player frozen
# %arg% - Command argument on error  - Not supported yet

# Enable auto bans? Set to true if you want this enabled.
autoban: true
# Message that displays in chat (use %player%)
autoban-msg: "§e%player% §fwas §cbanned§f because they logged out while frozen."
# Message that displays for player.
autoban-reason: "§cYou are banned for: §bLogging out while frozen"
# Format for freeze.
format: "§8§l(§bFreeze§8)§r "
# Allow commands while frozen? Default is false (No)
commands-frozen: false
# Allow frozen player to attack? Default is false
attack-frozen: false
# Allow frozen player to be attacked? Default is false
attacked-frozen: false
# Allow frozen players to use /msg and such? Default is true (true = allow /msg 's)
dms-frozen: true
# Frozen tag Defaults to true, if false, normal player tag will be shown.
frozen-tag: true
# Frozen message, aka when frozen (one time)
frozen-msg: true
# Text next to player name while frozen
format-tag: "§c§lFROZEN§r "
# Frozen title message
title-msg: true
# Frozen actionbar message
action-msg: true
# Timer - Idea, not made yet.
timer: 300 # 5 minutes
timer-after: "autoban" # autoban false kick warn

# MESSAGES  - Set each to false to disable the feature entirely (If not a setting above^)
error-hit: "§cYou can't hit frozen Players." # Supported
error-attack: "§cYou can't hit players while frozen" # Supported
error-noperm: "§cMissing permissions: freeze or freeze.command" # Unsupported
error-frozen: "§cThis player is already frozen." # Supported
error-frozen-msg: "§cYou are now frozen! Listen to staff."
error-immune: "§cThis player is immune." # Supported
error-provideArgument: "§cError, provide a §e%arg%"
error-player: "§cCould not find player: §e%arg%" # Unsupported
error-onjoin: "§cYou are Frozen" # Supported
error-title: "§cYou are Frozen" # Supported
error-actionbar: "§cDo not log out" # Supported
